name: .NET

on:
  push:
  
env:
  BRANCH_NAME: 'feature/this_is_a_test'
  # ${{ github.head_ref || github.ref_name }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      shell: bash
      run: echo "BRANCH_NAME=${BRANCH_NAME//_/-}" >> $GITHUB_ENV
    - name: Test
      run: echo $BRANCH_NAME
