name: .NET

on:
  push:
  
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      run: bash echo "BRANCH_NAME=$(echo $GITHUB_SHA | cut -c 1-2)" >> $GITHUB_ENV
    - name: Test
      run: echo $BRANCH_NAME
